default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--check"]

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--check"]
        language_version: python3.9

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args: [
          --namespace-packages,
          --explicit-package-bases,
          --ignore-missing-imports,
          --install-types,
          --non-interactive
        ]
