# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Omnisolver
site_author: "Konrad Jałowiecki & Łukasz Pawela"
copyright: ""
theme:
  name: material
  logo: assets/logo.png
  palette:
    primary: custom
  features:
    - navigation.tabs
    - navigation.tracking
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
nav:
  - User guide: userguide.md
  - Solver creator guide: creatorguide.md
  - Reference manual:
    - omnisolver.common.cmd: reference/omnisolver_common_cmd.md
    - omnisolver.common.plugin: reference/omnisolver_common_plugin.md
    - omnisolver.common.serialization: reference/omnisolver_common_serialization.md
  - Plugin list: plugins.md
plugins:
  - search
  - mike:
      canonical_version: latest
      version_selector: true
  - termynal:
      prompt_literal_start:
        - "$"
  - mkdocstrings:
      handlers:
        python:
          options:
            annotation_path: brief
            heading_level: 2
            show_source: false
            show_root_toc_entry: false
            show_signature_annotations: true
            members_order: source
            separate_signature: true
            docstring_options:
              ignore_init_summary: true
              merge_init_into_class: true
              show_docstring_returns: true
  # - with-pdf:
  #      render_js: true
  #      cover_subtitle: "An extensible interface to Ising spin–glass and QUBO solvers"
repo_name: Omnisolver
repo_url: https://github.com/euro-hpc-pl/omnisolver
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
