# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Omnisolver
site_author: "Konrad Jałowiecki & Łukasz Pawela"
copyright: ""
theme:
  name: material
  logo: assets/logo.png
  palette:
    primary: custom
  features:
    - navigation.tabs
    - navigation.tracking
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
nav:
  - User guide: userguide.md
  - Solver creator guide: creatorguide.md
  - Reference manual: reference.md
  - Plugin list: plugins.md
plugins:
  - search
  - with-pdf:
      cover_subtitle: "An extensible interface to Ising spin–glass and QUBO solvers"
  - mike:
      canonical_version: latest
      version_selector: true
  - termynal:
      prompt_literal_start:
        - "$"
repo_name: Omnisolver
repo_url: https://github.com/euro-hpc-pl/omnisolver
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
